version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    open-pull-requests-limit: 1
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    versioning-strategy: "increase"
    open-pull-requests-limit: 1
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    versioning-strategy: "increase"
    open-pull-requests-limit: 1
