version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
    versioning-strategy: "increase"
