name: Create Release
env:
  MILESTONE: ${{ github.event.milestone.title }}
on:
  milestone:
    types:
      - closed
permissions:
  contents: write
  issues: read
  pull-requests: read
jobs:
  create-release:
    name: Create Release
    uses: WyriHaximus/github-workflows/.github/workflows/package-craft-release.yaml@main
    with:
      milestone: ${{ github.event.milestone.title }}
      description: ${{ github.event.milestone.title }}
